name: Build Geode Mod
on: [workflow_dispatch, push]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Android
          os: ubuntu-latest
          target: Android
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    steps:
      - consts: checkout
        uses: actions/checkout@v4
      - name: Build Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          target: ${{ matrix.config.target }}
